### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [nzgr/utilita#1]
1. Для начала допишите тесты. Пока у Вас не только нет тестов, но и из-за синтаксической ошибки в test.kt проект не собирается.
1. Вторая проблема из-за которой ничего не запустится: для обоих позиционных аргументов (`word` и `inputName`) Вы указали индекс 1. Индекс - это порядковый номер (с 0) конкретного аргумента среди списка позиционных аргументов. Для первого аргумента (`word`) он должен быть равен 0.
1. Зачем Вы указали `metaVar` для `-r`? Ведь `-r` - `boolean` флаг, у него не должно быть значения.
1. Все `boolean` аргументы должны быть необязательными.
1. https://github.com/nzgr/utilita/blob/cfd34ddaac7d9ea6dea196f5caed529d03069ed1/src/grep/probnyy.kt#L11-L12 Зачем Вам этот вложенный класс?
1. https://github.com/nzgr/utilita/blob/cfd34ddaac7d9ea6dea196f5caed529d03069ed1/src/grep/probnyy.kt#L6 Зачем это класс `open`?
1. https://github.com/nzgr/utilita/blob/cfd34ddaac7d9ea6dea196f5caed529d03069ed1/src/grep/probnyy.kt#L7-L9 Почему они `var` и почему Вы не объявили их прямо в заголовке класса? Сейчас они у Вас всегда `false`.
1. Вместо того, чтобы рассматривать все 8 возможных комбинаций флагов, лучше обработать их независимо. С этим Вам может помочь то, что из строки легко сделать регулярное выражение, которое будет искать эту строку.
1. Выводить результат утилита должна на консоль. Так как сделано у Вас работать в принципе не будет, потому что `BufferedWriter` - это не промежуточный буфер, в который можно писать, а потом вывести куда-то в другое место. Здесь лучше всего будет вернуть из Вашего метода `constructor` (очень странное название, кстати, лучше бы его поменять на что-то осмысленное) список подходящих строк. А потом, уже из `launch` в цикле напечатать эти строки в консоль. Так и тесты писать будет проще.

**Comment by nenailya** [comment]
здравствуйте! исправила всё кроме 8 и написала тест

**Comment by maximpetrov** [comment]
1. Напишите, всё-таки внятный `usage` для `word` и `inputName`.
1. https://github.com/nzgr/utilita/blob/f21f0defb671bc7fce3646e2d8aae84f91c1302c/src/grep/UtilitaLauncher.java#L55 Зачем Вы приводите к `ArrayList` и почему он без указания типа? Почему просто `List` не использовать?
1. Из самого метода `grep` тоже лучше возвращать `List`, а не `MutableList`.
1. Почему тесты у Вас в папке .idea?
1. Не стоит использовать абсолютные пути в тестах, иначе работать они будут только у Вас на компьютере.
1. Почему Вы не написали тесты для всех 8 комбинаций флагов? И почему Вы используете флаг `regex`, но настоящее регулярное выражение не подставляете?
1. Как Вы сами написали, пункт 8 ещё в силе.

**Comment by nenailya** [comment]
исправила всё (кроме восьмого)

**Comment by maximpetrov** [comment]
1. https://github.com/nzgr/utilita/blob/6bca7cceffc102615101e427e51ba13c676b78da/src/grep/probnyy.kt#L70 Здесь не нужен `toList()`.
1. Зачем Вы иногда делаете `trim()`? Вдруг кто-то будет искать именно строку с пробелами.

**Comment by nenailya** [comment]
исправила
